<?php

namespace AppBundle\DataFixtures\ORM;

use BookshopBundle\Factory\BookFactory;
use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\DependencyInjection\ContainerAwareInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;

class LoadBookData extends AbstractFixture implements ContainerAwareInterface, OrderedFixtureInterface
{
    /**
     * @var ContainerInterface
     */
    private $container;

    public function setContainer(ContainerInterface $container = null)
    {
        $this->container = $container;
    }

    public function load(ObjectManager $em)
    {
        foreach ($this->getData() as $book) {
            $bookshop = BookFactory::create($book[0], $book[1]);
            $em->persist($bookshop);
        }

        $em->flush();
    }

    public function getOrder() : int
    {
        return 1;
    }

    private function getData() : array
    {
        return [
            ['Grey. Pięćdziesiąt twarzy Greya oczami Christiana', 'James E L'],
            ['Dziewczyna z pociągu', 'Hawkins Paula'],
            ['Niebezpieczne związki Bronisława Komorowskiego', 'Sumliński Wojciech'],
            ['Pogromca lwów', 'Lackberg Camilla'],
            ['Co nas nie zabije', 'Lagercrantz David'],
            ['Zniszcz ten dziennik', 'Smith Keri'],
            ['To nie książka', 'Smith Keri'],
            ['Elementarz stylu', 'Tusk Katarzyna'],
            ['Ukryte terapie. Czego ci lekarz nie powie', 'Zięba Jerzy'],
            ['Red Lipstick Monster. Tajniki makijażu', 'Grzelakowska-Kostoglu Ewa'],
            ['Złe psy. W imię zasad', 'Vega Patryk'],
            ['Dotyk Crossa. Tom 4. Wybór Crossa', 'Day Sylvia'],
            ['Uległość', 'Houellebecq Michel'],
            ['Tajemny ogród. Rysuj, koloruj, przeżywaj przygody', 'Basford Johanna'],
            ['Pakiet Teodor Szacki: Uwikłanie / Ziarno prawdy / Gniew', 'Miłoszewski Zygmunt'],
            ['Cztery żywioły. Tom 2. Okularnik', 'Bonda Katarzyna'],
            ['Uniwersum Metro 2033. Metro 2035', 'Glukhovsky Dmitry'],
            ['Magia sprzątania', 'Kondo Marie'],
            ['Jadłonomia. Kuchnia roślinna. 100 przepisów nie tylko dla wegan', 'Dymek Marta'],
            ['Najgorszy człowiek na świecie', 'Halber Małgorzata'],
            ['Naciśnij mnie', 'Tullet Herve'],
            ['Teodor Szacki. Tom 1. Uwikłanie', 'Miłoszewski Zygmunt'],
            ['Teodor Szacki. Tom 3. Gniew', 'Miłoszewski Zygmunt'],
            ['Jeśli zostanę. Tom 2. Wróć, jeśli pamiętasz', 'Forman Gayle'],
            ['House of Cards. Tom 1', 'Dobbs Michael'],
            ['Wierszyki ćwiczące języki, czyli rymowanki logopedyczne dla dzieci', 'Galewska-Kustra Marta, Szwajkowska Elżbieta, Szwajkowski Witold'],
            ['Pakiet: Pięćdziesiąt twarzy Greya. Część 1-3', 'James E L'],
            ['Bóg nigdy nie mruga', 'Brett Regina'],
            ['Czas pokaże', 'Ficner-Ogonowska Anna'],
            ['Feblik', 'Musierowicz Małgorzata'],
            ['Jak mówić, żeby dzieci nas słuchały. Jak słuchać, żeby dzieci do nas mówiły', 'Faber Adele, Mazlish Elaine'],
            ['What if? A co gdyby?', 'Munroe Randall'],
            ['Masa o porachunkach polskiej mafii', 'Górski Artur'],
            ['Hubert Meyer. Tom 1. Sprawa Niny Frank', 'Bonda Katarzyna'],
            ['Moje wypieki. Wielki powrót', 'Świątkowska Dorota'],
            ['Harry Potter. Książka do kolorowania', 'Opracowanie zbiorowe'],
            ['Wiedźmin. Tom 1. Ostatnie życzenie', 'Sapkowski Andrzej'],
            ['Złe psy. Po ciemnej stronie mocy', 'Vega Patryk'],
            ['Jak zamieszać w swoim życiu, czyli koktajle dla zdrowia i urody', 'Błażejewska Katarzyna'],
            ['W dżungli codzienności', 'Pawlikowska Beata'],
            ['Resortowe dzieci. Tom 2. Służby', 'Kania Dorota, Targalski Jerzy, Marosz Maciej'],
            ['Cztery żywioły. Tom 1. Pochłaniacz', 'Bonda Katarzyna'],
            ['Umrzeć po raz drugi', 'Gerritsen Tess'],
            ['Smak szczęścia, czyli o dietach, pielęgnacji urody w zgodzie z naturą i szukaniu piękna w sobie', 'Maciąg Agnieszka'],
            ['Mickey Bolitar. Tom 3. Odnaleziony', 'Coben Harlan'],
            ['Ciemniejsza strona Greya', 'James E L'],
            ['Blackout', 'Elsberg Marc'],
            ['Pokolenie Ikea', 'Piotr C.'],
            ['Zezia i wszystkie problemy świata', 'Chylińska Agnieszka'],
            ['Księgi Jakubowe', 'Tokarczuk Olga'],
            ['Plastusiowy pamiętnik', 'Kownacka Maria'],
            ['Potęga podświadomości', 'Murphy Joseph'],
            ['Ja, Fronczewski', 'Fronczewski Piotr, Mastalerz Marcin'],
            ['Edward Popielski. Tom 7. Arena szczurów', 'Krajewski Marek'],
            ['Simona. Opowieść o niezwyczajnym życiu Simony Kossak', 'Kamińska Anna'],
            ['Nowe oblicze Greya', 'James E L'],
            ['Hubert Meyer. Tom 3. Florystka', 'Bonda Katarzyna'],
            ['Smak świąt', 'Maciąg Agnieszka'],
            ['Magiczne drzewo. Tom 7. Świat ogromnych', 'Maleszka Andrzej'],
            ['Zniszcz ten dziennik. Wszędzie', 'Smith Keri'],
            ['Rywalki. Tom 4. Następczyni', 'Cass Kiera'],
            ['Prawo milenium. Księga 2. Anioł burz', 'Canavan Trudi'],
            ['Żelazne damy. Kobiety, które zbudowały Polskę', 'Janicki Kamil'],
            ['Krew na śniegu', 'Nesbo Jo'],
            ['Mapy', 'Mizielińska Aleksandra, Mizieliński Daniel'],
            ['Szczygieł', 'Tartt Donna'],
            ['Doktor Dolittle i jego zwierzęta', 'Lofting Hugh'],
            ['Kolorowy trening antystresowy. Wzory i ornamenty', 'Opracowanie zbiorowe'],
            ['Australijczyk', 'Niedźwiecki Marek'],
            ['Zaczarowany las. Koloruj, szukaj symboli, odkryj tajemnicę', 'Basford Johanna'],
            ['Genialni. Lwowska szkoła matematyczna', 'Urbanek Mariusz'],
            ['Wiedźmin. Tom 2. Miecz przeznaczenia', 'Sapkowski Andrzej'],
            ['Jesteś cudem', 'Brett Regina'],
            ['Kuchnia Fit', 'Gaca Konrad'],
            ['Ja, inkwizytor. Kościany galeon', 'Piekara Jacek'],
            ['Jaglany detoks. Oczyść organizm w 7 dni!', 'Zaremba Marek'],
            ['Hubert Meyer. Tom 2. Tylko martwi nie kłamią', 'Bonda Katarzyna'],
            ['Ciało i ducha ratować żywieniem', 'Dąbrowska Ewa'],
            ['Idę tam gdzie idę. Autobiografia + plakat', 'Staszewski Kazik, Księżyk Rafał'],
            ['Pakiet: Camilla Lackberg. Tom 1-4', 'Lackberg Camilla'],
            ['Zostań, jeśli kochasz', 'Forman Gayle'],
            ['Masa o bossach polskiej mafii', 'Górski Artur'],
            ['Pod ziemią. Pod wodą', 'Mizielińska Aleksandra, Mizieliński Daniel'],
            ['Antystresowe, kreatywne kolorowanie dla dorosłych. Piękne ogrody', 'Opracowanie zbiorowe'],
            ['Losing hope', 'Hoover Colleen'],
            ['Tron z czaszek. Księga 2', 'Brett Peter V.'],
            ['Wszystko za Everest', 'Krakauer Jon'],
            ['Przesunąć horyzont', 'Wojciechowska Martyna'],
            ['Love, Rosie', 'Ahern Cecelia'],
            ['Masa o pieniądzach polskiej mafii', 'Górski Artur'],
            ['Szału nie ma, jest Rak', 'Jabłońska Katarzyna, Kaczkowski Jan'],
            ['Blondynka na językach. Angielski brytyjski + CD', 'Pawlikowska Beata'],
            ['Więcej krwi', 'Nesbo Jo'],
            ['Futu.re', 'Glukhovsky Dmitry'],
            ['Jak przestać się martwić i zacząć żyć', 'Carnegie Dale'],
            ['10 niesamowitych przygód Neli', 'Nela'],
            ['Kuba', 'Błaszczykowski Jakub, Domagalik Małgorzata'],
            ['Odstresuj się. Połącz kropki. Dzieła sztuki, krajobrazy i pojazdy', 'Opracowanie zbiorowe'],
            ['Baśnie Barda Beedle’a', 'Rowling J.K.'],
            ['Już mnie nie oszukasz', 'Coben Harlan'],
            ['Za zamkniętymi drzwiami', 'Paris B.A.'],
            ['13 powodów', 'Asher Jay'],
            ['Food Pharmacy', 'Aurell Lina Nertby, Clase Mia'],
            ['Fantastyczne zwierzęta i jak je znaleźć. Leksykon', 'Rowling J.K.'],
            ['Sekretne życie drzew', 'Wohlleben Peter'],
            ['Harry Hole. Tom 11. Pragnienie', 'Nesbo Jo'],
            ['Duchowe życie zwierząt', 'Wohlleben Peter'],
            ['Quidditch przez wieki', 'Rowling J.K.'],
            ['Mitologia nordycka', 'Gaiman Neil'],
            ['Smak zdrowia', 'Maciąg Agnieszka'],
            ['Sztuka kochania', 'Wisłocka Michalina'],
            ['Joanna Chyłka. Tom 5. Inwigilacja', 'Mróz Remigiusz'],
            ['Był sobie pies', 'Cameron Bruce W.'],
            ['Duchowe życie zwierząt (edycja ilustrowana)', 'Wohlleben Peter'],
            ['Magia olewania', 'Knight Sarah'],
            ['Zielone koktajle. 365 przepisów', 'Zielone koktajle'],
            ['Mali bogowie. O znieczulicy polskich lekarzy', 'Reszka Paweł'],
            ['Zapisane w wodzie', 'Hawkins Paula'],
            ['Światło między oceanami', 'Stedman M.L.'],
            ['Małe życie', 'Yanagihara Hanya'],
            ['Dziewczyna, którą kochałeś', 'Moyes Jojo'],
            ['Fantastyczne zwierzęta i jak je znaleźć. Oryginalny scenariusz', 'Rowling J.K.'],
            ['Nowa Jadłonomia. Roślinne przepisy z całego świata', 'Dymek Marta'],
            ['Deniwelacja', 'Mróz Remigiusz'],
            ['Nela i skarby Karaibów', 'Nela'],
            ['Sekretne życie drzew (edycja ilustrowana)', 'Wohlleben Peter'],
            ['W kręgach władzy. Tom 1. Wotum nieufności', 'Mróz Remigiusz'],
            ['Ukryte terapie. Czego ci lekarz nie powie. Część 2', 'Zięba Jerzy'],
            ['Zdrowe koktajle', 'Chodakowska Ewa, Kavoukis Lefteris, Kielak Marta'],
            ['Sekrety urody Koreanek. Elementarz pielęgnacji', 'Cho Charlotte'],
            ['Michalina Wisłocka', 'Ozminkowski Violetta'],
            ['Rzecz o ptakach', 'Strycker Noah'],
            ['Od oddechu do oddechu', 'Młynarski Wojciech'],
            ['Hygge. Duńska sztuka szczęścia', 'Tourell Soderberg Marie'],
            ['Czerwień jarzębin', 'Michalak Katarzyna'],
            ['Życie na pełnej petardzie', 'Kaczkowski Jan, Żyłka Piotr'],
            ['Tu byłem. Tony Halik', 'Wlekły Mirosław'],
            ['Małe wielkie rzeczy', 'Picoult Jodi'],
            ['Pax', 'Pennypacker Sara'],
            ['Joanna Chyłka. Tom 1. Kasacja', 'Mróz Remigiusz'],
            ['Król', 'Twardoch Szczepan'],
            ['Oszukana', 'Link Charlotte'],
            ['Kiedy odszedłeś', 'Moyes Jojo'],
            ['Harry Potter i Przeklęte Dziecko. Część 1-2', 'Rowling J.K., Tiffany John, Thorne Jack'],
            ['Prowadź swój pług przez kości umarłych', 'Tokarczuk Olga'],
            ['Szklany tron. Tom 5. Imperium burz', 'Maas Sarah J.'],
            ['Mleko i miód. Milk and Honey', 'Kaur Rupi'],
            ['Zanim się pojawiłeś', 'Moyes Jojo'],
            ['Chata', 'Young William P.'],
            ['Kwiat paproci. Tom 3. Żerca', 'Miszczuk Katarzyna Berenika'],
            ['Ciało i ducha ratować żywieniem', 'Dąbrowska Ewa'],
            ['Lipowo. Tom 8. Czarne narcyzy', 'Puzyńska Katarzyna'],
            ['Jeszcze jeden oddech', 'Kalanithi Paul'],
            ['Wzgórze psów', 'Żulczyk Jakub'],
            ['Joanna Chyłka. Tom 4. Immunitet', 'Mróz Remigiusz'],
            ['Szepty kamieni. Historie z opuszczonej Islandii', 'Lenard Berenika, Mikołajczak Piotr'],
            ['Skin Coach. Twoja droga do pięknej i zdrowej skóry', 'Społowicz Bożena'],
            ['Shantaram', 'Roberts Gregory David'],
            ['Hygge. Klucz do szczęścia', 'Wiking Meik'],
            ['Czary codzienności. Tom 3. Słoneczna przystań', 'Krawczyk Agnieszka'],
            ['Czereśnie zawsze muszą być dwie', 'Witkiewicz Magdalena'],
            ['Joanna Chyłka. Tom 2. Zaginięcie', 'Mróz Remigiusz'],
            ['Sztuka kochania', 'Wisłocka Michalina'],
            ['Czerwona Królowa. Tom 3. Królewska klatka', 'Aveyard Victoria'],
            ['Joanna Chyłka. Tom 3. Rewizja', 'Mróz Remigiusz'],
            ['Siostry', 'Douglas Claire'],
            ['Najlepiej w życiu ma twój kot. Listy', 'Szymborska Wisława'],
            ['Dasz radę. Ostatnia rozmowa', 'Kaczkowski Jan, Podsadecka Joanna'],
            ['Dieta uzdrawiająca organizm', 'Makarowska Magdalena'],
            ['Opowieść podręcznej', 'Atwood Margaret'],
            ['Naucz się żyć', 'Billmark Mats, Billmark Susan'],
            ['Historia wewnętrzna. Jelita - najbardziej fascynujący organ naszego ciała', 'Enders Giulia'],
            ['Moje pierwsze 100 słów', 'Opracowanie zbiorowe'],
            ['Confess', 'Hoover Colleen'],
            ['Bóg w wielkim mieście', 'Olubińska Katarzyna'],
            ['Dwór cierni i róż. Tom 2. Dwór mgieł i furii', 'Maas Sarah J.'],
            ['Post Daniela z uzdrawiającą dietą dr Ewy Dąbrowskiej. Jak skutecznie oczyścić ciało i ducha', 'Dajka Krystyna, Piórkowski Łukasz'],
            ['Potęga podświadomości', 'Murphy Joseph'],
            ['Jak pokochać centra handlowe', 'Fiedorczuk Natalia'],
            ['Spod zamarzniętych powiek', 'Szczepański Dominik, Bielecki Adam'],
            ['Niebezpieczne związki Andrzeja Leppera. Kto naprawdę go zabił?', 'Sumliński Wojciech'],
            ['Dekalog księdza Jana Kaczkowskiego', 'Kaczkowski Jan, Szkarpetowska Katarzyna'],
            ['Dzieje Polski. Tom 3. 1340-1468 Królestwo zwycięskiego orła', 'Nowak Andrzej'],
            ['Behawiorysta', 'Mróz Remigiusz'],
            ['Pucio mówi pierwsze słowa', 'Galewska-Kustra Marta'],
            ['Opowieści z Akademii Nocnych Łowców', 'Res-Brennan Sarah, Johnson Maureen, Wasserman Robin, Clare Cassandra'],
            ['Manwhore. Tom 2. Manwhore + 1', 'Evans Katy'],
            ['Najmroczniejszy sekret', 'Marwood Alex'],
            ['Przywracać zdrowie żywieniem', 'Dąbrowska Ewa'],
            ['Twoje kompetentne dziecko', 'Juul Jesper'],
            ['Vestmanna. Tom 1. Enklawa', 'Logmansbo Ove (Remigiusz Mróz)'],
            ['Dziecko Bridget Jones. Dziennik', 'Fielding Helen'],
            ['Vestmanna. Tom 3. Prom', 'Logmansbo Ove (Remigiusz Mróz)'],
            ['Brulion zabaw dla każdego', 'Opracowanie zbiorowe'],
        ];
    }
}
